"""Freshness overview of every data source behind the MCP tools."""

import os
from datetime import UTC, datetime
from pathlib import Path

from .knowledge import KnowledgeBase
from .sources import SOURCES

KVG_FILE = Path(__file__).resolve().parents[2] / "data" / "kvg_minimum_premiums_2026.csv"


def stale_after_days() -> int:
    try:
        return int(os.environ.get("STALE_AFTER_DAYS", "30"))
    except ValueError:
        return 30


def _age_days(timestamp: str | None, now: datetime) -> float | None:
    if not timestamp:
        return None
    return round((now - datetime.fromisoformat(timestamp)).total_seconds() / 86400, 1)


def _state(last_refresh, last_failure, age, threshold) -> str:
    if last_refresh is None:
        return "missing"
    if last_failure and last_failure > last_refresh:
        return "failed"
    return "stale" if age is not None and age > threshold else "fresh"


def get_status(database: KnowledgeBase | None = None, now: datetime | None = None) -> dict:
    """One row per approved source, plus read-only rows for static data files."""
    now = now or datetime.now(UTC)
    threshold = stale_after_days()
    with (database or KnowledgeBase()).connect() as db:
        saved = {
            (r["level"], r["source"]): r
            for r in db.execute(
                """
                SELECT s.level, s.source, s.crawled_at,
                       (SELECT COUNT(*) FROM passages p
                        WHERE p.level = s.level AND p.source = s.source) AS passages
                FROM sources s
                """
            )
        }
        failures = {(r["level"], r["source"]): r for r in db.execute("SELECT * FROM failures")}

    rows = []
    for level, entries in SOURCES.items():
        for name, entry in entries.items():
            row = saved.get((level, name))
            failure = failures.get((level, name))
            last_refresh = row["crawled_at"] if row else None
            last_failure = failure["failed_at"] if failure else None
            age = _age_days(last_refresh, now)
            rows.append({
                "kind": "crawled",
                "level": level,
                "source": name,
                "authority": entry.authority,
                "url": entry.url,
                "last_refresh": last_refresh,
                "age_days": age,
                "state": _state(last_refresh, last_failure, age, threshold),
                "last_failure": last_failure,
                "error": failure["error"] if failure else None,
                "passages": row["passages"] if row else 0,
                "refreshable": True,
            })

    if KVG_FILE.exists():
        modified = datetime.fromtimestamp(KVG_FILE.stat().st_mtime, UTC).isoformat()
        age = _age_days(modified, now)
        rows.append({
            "kind": "static",
            "level": "federal",
            "source": "kvg_minimum_premiums",
            "authority": "BAG (regenerated by GitHub Actions workflow)",
            "url": None,
            "last_refresh": modified,
            "age_days": age,
            "state": _state(modified, None, age, threshold),
            "last_failure": None,
            "error": None,
            "passages": 0,
            "refreshable": False,
        })
    return {"generated_at": now.isoformat(), "stale_after_days": threshold, "sources": rows}
